/*
 * Copyright (C) 2017 Roger G. Coscojuela
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package vista;

import javax.swing.JDialog;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JTextArea;
import javax.swing.JTextField;

public class gui extends javax.swing.JFrame {

    JDialog about;
    String lsp = System.getProperty("line.separator");
    String separator = "*";

    public gui() {
        initComponents();
        //Rellenamos procedimiento
        ((JComponent) TaskPaneEnlaceMira.getContentPane()).setBorder(BorderFactory.createEmptyBorder());
        textFieldEnlace = new JTextField();
        TaskPaneEnlaceMira.add(textFieldEnlace);

        //Rellenamos gestion
        ((JComponent) TaskPaneGestion.getContentPane()).setBorder(BorderFactory.createEmptyBorder());
        textAreaGestion = new JTextArea("Gestion!");
        textAreaGestion.setLineWrap(true);
        textAreaGestion.setRows(10);

        TaskPaneGestion.add(textAreaGestion);
        copiarAPruebas = new JButton("Copiar a resumen de pruebas");
        copiarAPruebas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiarAPruebas(evt);
            }
        });
        TaskPaneGestion.add(copiarAPruebas);

        //Rellenamos resumen
        textAreaResumenPruebas = new JTextArea();
        TaskPaneResumenDePruebas.add(textAreaResumenPruebas);

        //Rellenamos contacto cliente
        textAreaContacto = new JTextArea("Roger!");
        TaskPaneContacto.add(textAreaContacto);

        //Rellenamos siguiente
        textAreaSiguiente = new JTextArea("Siguiente!");
        TaskPaneSiguiente.add(textAreaSiguiente);

        about = new About2(this, true);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jXTaskPaneContainer = new org.jdesktop.swingx.JXTaskPaneContainer();
        TaskPaneEnlaceMira = new org.jdesktop.swingx.JXTaskPane();
        TaskPaneGestion = new org.jdesktop.swingx.JXTaskPane();
        TaskPaneResumenDePruebas = new org.jdesktop.swingx.JXTaskPane();
        TaskPaneContacto = new org.jdesktop.swingx.JXTaskPane();
        TaskPaneSiguiente = new org.jdesktop.swingx.JXTaskPane();
        jPanel1 = new javax.swing.JPanel();
        copiarAPortapapeles = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        FileItem = new javax.swing.JMenu();
        exitItemMenu = new javax.swing.JMenuItem();
        setingsItem = new javax.swing.JMenu();
        helpItem = new javax.swing.JMenu();
        aboutItemMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jXTaskPaneContainer.setBackground(new java.awt.Color(240, 240, 240));
        jXTaskPaneContainer.setAutoscrolls(true);

        TaskPaneEnlaceMira.setTitle("Procedimiento");
        jXTaskPaneContainer.add(TaskPaneEnlaceMira);

        TaskPaneGestion.setTitle("Gestión");
        jXTaskPaneContainer.add(TaskPaneGestion);

        TaskPaneResumenDePruebas.setToolTipText("");
        TaskPaneResumenDePruebas.setCollapsed(true);
        TaskPaneResumenDePruebas.setName(""); // NOI18N
        TaskPaneResumenDePruebas.setTitle("Resumen de pruebas");
        jXTaskPaneContainer.add(TaskPaneResumenDePruebas);

        TaskPaneContacto.setCollapsed(true);
        TaskPaneContacto.setTitle("Contacto Cliente");
        jXTaskPaneContainer.add(TaskPaneContacto);

        TaskPaneSiguiente.setTitle("Siguiente");
        jXTaskPaneContainer.add(TaskPaneSiguiente);

        jScrollPane1.setViewportView(jXTaskPaneContainer);

        copiarAPortapapeles.setText("Copiar a portapapeles");
        copiarAPortapapeles.setMargin(null);
        copiarAPortapapeles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiarAPortapapelesActionPerformed(evt);
            }
        });

        jButton2.setText("Procesar desde portapapeles");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jButton2)
                .addContainerGap(310, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(413, Short.MAX_VALUE)
                    .addComponent(copiarAPortapapeles)
                    .addContainerGap(11, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(copiarAPortapapeles)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        FileItem.setText("File");

        exitItemMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        exitItemMenu.setText("Exit");
        exitItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitItemMenuActionPerformed(evt);
            }
        });
        FileItem.add(exitItemMenu);

        jMenuBar.add(FileItem);

        setingsItem.setText("Settings");
        jMenuBar.add(setingsItem);

        helpItem.setText("Help");

        aboutItemMenu.setText("About");
        aboutItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutItemMenuActionPerformed(evt);
            }
        });
        helpItem.add(aboutItemMenu);

        jMenuBar.add(helpItem);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItemMenuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitItemMenuActionPerformed

    private void aboutItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutItemMenuActionPerformed
        about.setVisible(true);
    }//GEN-LAST:event_aboutItemMenuActionPerformed

    private void copiarAPortapapelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiarAPortapapelesActionPerformed
        int fillerSize = 50;
        String nota = fillText(TaskPaneEnlaceMira.getTitle(), separator, fillerSize) + lsp + textFieldEnlace.getText() + lsp + lsp;
        nota = nota + fillText(TaskPaneGestion.getTitle(), separator, fillerSize) + lsp + textAreaGestion.getText() + lsp + lsp;
        nota = nota + fillText(TaskPaneResumenDePruebas.getTitle(), separator, fillerSize) + lsp + textAreaResumenPruebas.getText() + lsp + lsp;
        nota = nota + fillText(TaskPaneSiguiente.getTitle(), separator, fillerSize) + lsp + textAreaSiguiente.getText();
        Clipboard clipboard = getToolkit().getSystemClipboard();
        clipboard.setContents(new StringSelection(nota), null);
    }//GEN-LAST:event_copiarAPortapapelesActionPerformed

    private void copiarAPruebas(java.awt.event.ActionEvent evt) {
        if (textAreaResumenPruebas.getText().equals("")) {
            textAreaResumenPruebas.setText(textAreaGestion.getText());
        } else {
            textAreaResumenPruebas.setText(textAreaResumenPruebas.getText().concat(lsp).concat(textAreaGestion.getText()));
        }
    }

    private String fillText(String text, String fill, int size) {
        String result = text;
        while (result.length() < size) {
            result = fill + result;
            if (result.length() < size) {
                result = result + fill;
            }
        }
        return result;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu FileItem;
    private org.jdesktop.swingx.JXTaskPane TaskPaneContacto;
    private org.jdesktop.swingx.JXTaskPane TaskPaneEnlaceMira;
    private org.jdesktop.swingx.JXTaskPane TaskPaneGestion;
    private org.jdesktop.swingx.JXTaskPane TaskPaneResumenDePruebas;
    private org.jdesktop.swingx.JXTaskPane TaskPaneSiguiente;
    private javax.swing.JMenuItem aboutItemMenu;
    private javax.swing.JButton copiarAPortapapeles;
    private javax.swing.JMenuItem exitItemMenu;
    private javax.swing.JMenu helpItem;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXTaskPaneContainer jXTaskPaneContainer;
    private javax.swing.JMenu setingsItem;
    // End of variables declaration//GEN-END:variables

    //Custom variables declaration
    private JTextField textFieldEnlace;
    private JTextArea textAreaGestion;
    private JButton copiarAPruebas;
    private JTextArea textAreaResumenPruebas;
    private JTextArea textAreaContacto;
    private JTextArea textAreaSiguiente;
    //End of custom variables declaration
}
