/*
 * Copyright (C) 2017 Roger G. Coscojuela
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package vista;

import javax.swing.JDialog;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.Toolkit;

public class gui extends javax.swing.JFrame {

    JDialog about;
    String lsp = System.getProperty("line.separator");
    String separator = "*";

    public gui() {
        initComponents();
        about = new About2(this, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EnlaceMiraLabel = new javax.swing.JLabel();
        textEnlaceMiraa = new javax.swing.JTextField();
        GestionMiraaLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textGestionMiraa = new javax.swing.JTextArea();
        ResumenDePruebasLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextResumenPruebas = new javax.swing.JTextArea();
        botonCopiarAResumenDePruebas = new javax.swing.JButton();
        copiarAPortapapeles = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        siguienteLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextSiguiente = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileItem = new javax.swing.JMenu();
        exitItemMenu = new javax.swing.JMenuItem();
        setingsItem = new javax.swing.JMenu();
        helpItem = new javax.swing.JMenu();
        aboutItemMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EnlaceMiraLabel.setText("Enlace Miraa");

        GestionMiraaLabel.setText("Gestión Miraa");

        textGestionMiraa.setColumns(20);
        textGestionMiraa.setLineWrap(true);
        textGestionMiraa.setRows(5);
        jScrollPane1.setViewportView(textGestionMiraa);

        ResumenDePruebasLabel.setText("Resumen de pruebas");

        TextResumenPruebas.setColumns(20);
        TextResumenPruebas.setLineWrap(true);
        TextResumenPruebas.setRows(5);
        jScrollPane2.setViewportView(TextResumenPruebas);

        botonCopiarAResumenDePruebas.setText("Copiar a resumen de pruebas");
        botonCopiarAResumenDePruebas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCopiarAResumenDePruebasActionPerformed(evt);
            }
        });

        copiarAPortapapeles.setText("Copiar a portapapeles");
        copiarAPortapapeles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiarAPortapapelesActionPerformed(evt);
            }
        });

        jButton2.setText("Procesar desde portapapeles");

        siguienteLabel.setText("Siguiente");

        TextSiguiente.setColumns(20);
        TextSiguiente.setRows(2);
        jScrollPane3.setViewportView(TextSiguiente);

        FileItem.setText("File");

        exitItemMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        exitItemMenu.setText("Exit");
        exitItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitItemMenuActionPerformed(evt);
            }
        });
        FileItem.add(exitItemMenu);

        jMenuBar1.add(FileItem);

        setingsItem.setText("Settings");
        jMenuBar1.add(setingsItem);

        helpItem.setText("Help");

        aboutItemMenu.setText("About");
        aboutItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutItemMenuActionPerformed(evt);
            }
        });
        helpItem.add(aboutItemMenu);

        jMenuBar1.add(helpItem);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(EnlaceMiraLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textEnlaceMiraa, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(GestionMiraaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ResumenDePruebasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonCopiarAResumenDePruebas))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(copiarAPortapapeles))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(siguienteLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnlaceMiraLabel)
                    .addComponent(textEnlaceMiraa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GestionMiraaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResumenDePruebasLabel)
                    .addComponent(botonCopiarAResumenDePruebas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(siguienteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(copiarAPortapapeles)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItemMenuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitItemMenuActionPerformed

    private void aboutItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutItemMenuActionPerformed
        about.setVisible(true);
    }//GEN-LAST:event_aboutItemMenuActionPerformed

    private void botonCopiarAResumenDePruebasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCopiarAResumenDePruebasActionPerformed
        TextResumenPruebas.setText(TextResumenPruebas.getText() + lsp + (textGestionMiraa.getText()));
    }//GEN-LAST:event_botonCopiarAResumenDePruebasActionPerformed

    private void copiarAPortapapelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiarAPortapapelesActionPerformed
        int fillerSize = 50;
        String nota = fillText(EnlaceMiraLabel.getText(), separator, fillerSize) + lsp + textEnlaceMiraa.getText() + lsp + lsp;
        nota = nota + fillText(GestionMiraaLabel.getText(), separator, fillerSize) + lsp + textGestionMiraa.getText() + lsp + lsp;
        nota = nota + fillText(ResumenDePruebasLabel.getText(), separator, fillerSize) + lsp + TextResumenPruebas.getText() + lsp + lsp;
        nota = nota + fillText(siguienteLabel.getText(), separator, fillerSize) + lsp + TextSiguiente.getText();
        Clipboard clipboard = getToolkit().getSystemClipboard();
        clipboard.setContents(new StringSelection(nota), null);
    }//GEN-LAST:event_copiarAPortapapelesActionPerformed

    private String fillText(String text, String fill, int size) {
        String result = text;
        while (result.length() < size) {
            result = fill + result;
            if (result.length() < size) {
                result = result + fill;
            }
        }
        return result;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EnlaceMiraLabel;
    private javax.swing.JMenu FileItem;
    private javax.swing.JLabel GestionMiraaLabel;
    private javax.swing.JLabel ResumenDePruebasLabel;
    private javax.swing.JTextArea TextResumenPruebas;
    private javax.swing.JTextArea TextSiguiente;
    private javax.swing.JMenuItem aboutItemMenu;
    private javax.swing.JButton botonCopiarAResumenDePruebas;
    private javax.swing.JButton copiarAPortapapeles;
    private javax.swing.JMenuItem exitItemMenu;
    private javax.swing.JMenu helpItem;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenu setingsItem;
    private javax.swing.JLabel siguienteLabel;
    private javax.swing.JTextField textEnlaceMiraa;
    private javax.swing.JTextArea textGestionMiraa;
    // End of variables declaration//GEN-END:variables
}
